const SEMITONES={C:0,'C#':1,D:2,'D#':3,E:4,F:5,'F#':6,G:7,'G#':8,A:9,'A#':10,B:11};
const SAMPLE_ROOT='https://tonejs.github.io/audio/salamander/';
const SAMPLE_NOTES=['A0','C1','D#1','F#1','A1','C2','D#2','F#2','A2','C3','D#3','F#3','A3','C4','D#4','F#4','A4','C5','D#5','F#5','A5','C6','D#6','F#6','A6','C7','D#7','F#7','A7','C8'];
function midi(p){const m=p.match(/^([A-G]#?)(-?\d)$/);return(Number(m[2])+1)*12+SEMITONES[m[1]]}function sampleFile(p){return p.replace('#','s')+'.mp3'}
export class AudioEngine{
 constructor(){this.ctx=null;this.master=null;this.dry=null;this.wet=null;this.buffers=new Map();this.loading=null;this.sources=new Set();this.sampled=false}
 async init(){if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});this.master=this.ctx.createGain();this.master.gain.value=.78;this.dry=this.ctx.createGain();this.wet=this.ctx.createGain();this.wet.gain.value=.12;const convolver=this.ctx.createConvolver();convolver.buffer=this.makeImpulse(1.8,2.6);this.dry.connect(this.master);this.dry.connect(convolver);convolver.connect(this.wet);this.wet.connect(this.master);this.master.connect(this.ctx.destination)}if(this.ctx.state==='suspended')await this.ctx.resume();if(!this.loading)this.loading=this.loadSamples();await this.loading}
 makeImpulse(seconds,decay){const rate=this.ctx.sampleRate,len=Math.floor(rate*seconds),buf=this.ctx.createBuffer(2,len,rate);for(let c=0;c<2;c++){const d=buf.getChannelData(c);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,decay)*.32}return buf}
 async loadSamples(){const needed=['A1','C2','D#2','F#2','A2','C3','D#3','F#3','A3','C4','D#4','F#4','A4','C5','D#5','F#5','A5','C6'];let ok=0;await Promise.all(needed.map(async p=>{try{const r=await fetch(SAMPLE_ROOT+sampleFile(p),{mode:'cors'});if(!r.ok)throw Error(r.status);const b=await this.ctx.decodeAudioData(await r.arrayBuffer());this.buffers.set(p,b);ok++}catch(e){console.warn('Piano sample failed',p,e)}}));this.sampled=ok>=8}
 setVolume(v){if(this.master)this.master.gain.setTargetAtTime(Number(v),this.ctx.currentTime,.025)}
 nearest(pitch){const target=midi(pitch);let best=null,dist=99;for(const [p,b] of this.buffers){const d=Math.abs(midi(p)-target);if(d<dist){best=[p,b];dist=d}}return best}
 scheduleNote(pitch,when,duration,velocity=.7){if(!this.ctx)return;const hit=this.nearest(pitch);if(!hit)return;const[startPitch,buffer]=hit,start=Math.max(this.ctx.currentTime,when),source=this.ctx.createBufferSource(),gain=this.ctx.createGain(),filter=this.ctx.createBiquadFilter(),targetMidi=midi(pitch);source.buffer=buffer;source.playbackRate.value=Math.pow(2,(targetMidi-midi(startPitch))/12);filter.type='lowpass';filter.frequency.value=targetMidi<48?4200:targetMidi<64?6500:9000;filter.Q.value=.25;const register=targetMidi<48?.78:targetMidi>76?.9:1,peak=Math.max(.008,velocity*register);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(peak,start+.006);const release=Math.max(.75,Math.min(2.5,duration*.55+1));gain.gain.setValueAtTime(peak*.94,start+Math.min(duration*.8,.45));gain.gain.exponentialRampToValueAtTime(.0001,start+duration+release);source.connect(filter);filter.connect(gain);gain.connect(this.dry);source.start(start);source.stop(start+duration+release+.08);this.sources.add(source);source.onended=()=>this.sources.delete(source)}
 stopAll(){for(const s of this.sources){try{s.stop()}catch{}}this.sources.clear()}
}
