const SEMITONES={C:0,'C#':1,D:2,'D#':3,E:4,F:5,'F#':6,G:7,'G#':8,A:9,'A#':10,B:11};
function frequency(pitch){const m=pitch.match(/^([A-G]#?)(-?\d)$/);const midi=(Number(m[2])+1)*12+SEMITONES[m[1]];return 440*Math.pow(2,(midi-69)/12)}
export class AudioEngine{
 constructor(){this.ctx=null;this.master=null;this.dry=null;this.wet=null;this.voices=new Set()}
 async init(){if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});this.master=this.ctx.createGain();this.master.gain.value=.72;this.dry=this.ctx.createGain();this.wet=this.ctx.createGain();this.wet.gain.value=.16;const delay=this.ctx.createDelay(1);delay.delayTime.value=.105;const feedback=this.ctx.createGain();feedback.gain.value=.18;delay.connect(feedback);feedback.connect(delay);this.dry.connect(this.master);this.dry.connect(delay);delay.connect(this.wet);this.wet.connect(this.master);this.master.connect(this.ctx.destination)}if(this.ctx.state==='suspended')await this.ctx.resume()}
 setVolume(v){if(this.master)this.master.gain.setTargetAtTime(Number(v),this.ctx.currentTime,.025)}
 scheduleNote(pitch,when,duration,velocity=.7){if(!this.ctx)return;const start=Math.max(this.ctx.currentTime,when),f=frequency(pitch),gain=this.ctx.createGain(),body=this.ctx.createOscillator(),warm=this.ctx.createOscillator(),sparkle=this.ctx.createOscillator(),warmGain=this.ctx.createGain(),sparkleGain=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();body.type='triangle';warm.type='sine';sparkle.type='sine';body.frequency.value=f;warm.frequency.value=f*.5;sparkle.frequency.value=f*2;warmGain.gain.value=.16;sparkleGain.gain.value=.035;filter.type='lowpass';filter.frequency.value=Math.min(6500,1800+f*3);filter.Q.value=.45;const peak=Math.max(.006,velocity*.18);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(peak,start+.012);gain.gain.exponentialRampToValueAtTime(peak*.48,start+.13);gain.gain.exponentialRampToValueAtTime(.0001,start+Math.max(.35,duration+.65));body.connect(filter);warm.connect(warmGain);warmGain.connect(filter);sparkle.connect(sparkleGain);sparkleGain.connect(filter);filter.connect(gain);gain.connect(this.dry);body.start(start);warm.start(start);sparkle.start(start);const stop=start+Math.max(.4,duration+.7);body.stop(stop);warm.stop(stop);sparkle.stop(stop);const voice={body,warm,sparkle};this.voices.add(voice);body.onended=()=>this.voices.delete(voice)}
 stopAll(){for(const v of this.voices){try{v.body.stop();v.warm.stop();v.sparkle.stop()}catch{}}this.voices.clear()}
}
